
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



 
public class working extends javax.swing.JFrame {
String name;
int age;
int ind=0;
String ans[]=new String[100];
int count=0;
Connection con = null;
    Statement st = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String quesc[]=new String[100];
    
    
    

public void setName(String name){
    this.name=name;
    
}
public void setAge(int age,String name){
    this.age=age;
    this.name=name;
}
public void setAge(int i){
    this.age=i;
}
    /**
     * Creates new form working
     */
    public working() {
    this.setUndecorated(true);
        initComponents();
    this.setSize(1100,900);
    r1.setVisible(false);
    r2.setVisible(false);
    r3.setVisible(false);
    r4.setVisible(false);
    l1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bb1 = new javax.swing.ButtonGroup();
        j1 = new javax.swing.JDialog();
        ll1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        num = new javax.swing.JLabel();
        b100 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        b10 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        ll1.setFont(new java.awt.Font("Comic Sans MS", 2, 48)); // NOI18N

        javax.swing.GroupLayout j1Layout = new javax.swing.GroupLayout(j1.getContentPane());
        j1.getContentPane().setLayout(j1Layout);
        j1Layout.setHorizontalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ll1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        j1Layout.setVerticalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ll1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 980, 360));

        num.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 550, 50));

        b100.setText("Play Game");
        b100.setEnabled(false);
        b100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b100ActionPerformed(evt);
            }
        });
        getContentPane().add(b100, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, -1));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, 122, 38));

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow-right-icon.png"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 780, 70, 70));

        b10.setText("Test Result");
        b10.setEnabled(false);
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 789, -1, 40));

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Next-icon.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 770, 70, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOT-Chat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 2, 36))); // NOI18N

        l2.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N

        bb1.add(r4);
        r4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        r4.setText("Yes");

        bb1.add(r3);
        r3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        r3.setText("No");

        bb1.add(r1);
        r1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        r1.setText("Yes");

        bb1.add(r2);
        r2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        r2.setText("No");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setText("Animo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(r1)
                        .addGap(73, 73, 73)
                        .addComponent(r2)
                        .addGap(41, 41, 41)
                        .addComponent(r3)
                        .addGap(31, 31, 31)
                        .addComponent(r4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r2)
                        .addComponent(r3)
                        .addComponent(r4)))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 730, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botanical-dirt-illustration-1022923.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ln.setText(name);
connect(1);
l1.setEnabled(true);
l2.setText(quesc[count]);
r1.setText("Yes");
r2.setText("No");
r1.setVisible(true);
r2.setVisible(true);
r3.setVisible(false);
r4.setVisible(false);
count++;
q1validation();
jButton1.setEnabled(false);
bb1.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
l2.setText(quesc[count]);
if(count==1){
 r1.setText("Dairy Milk");
    r2.setText("5-Star");
    r3.setText("KitKat");
    r4.setText("Others");
   r3.setVisible(true);
r4.setVisible(true);
q2validation();
bb1.clearSelection();
}
else if(count==2){
r1.setText("Yes");
r2.setText("No");
r1.setVisible(true);
r2.setVisible(true);
r3.setVisible(false);
r4.setVisible(false);
bb1.clearSelection();
q3validation();
}
else if(count==3){
r1.setText("Noddy");
r2.setText("Shinchan");
r3.setText("Doraemon");
r4.setText("Hattori");
r1.setVisible(true);
r2.setVisible(true);

r3.setVisible(true);
r4.setVisible(true);
bb1.clearSelection();
q4validation();
}
else if(count==4){
r1.setText("Yes");
r2.setText("No");
r1.setVisible(true);
r2.setVisible(true);
r3.setVisible(false);
r4.setVisible(false);
bb1.clearSelection();
q5validation();
}
else if(count==5){
r1.setText("Indoor");
r2.setText("Outdoor");
r1.setVisible(true);
r2.setVisible(true);
bb1.clearSelection();
q6validation();
}
else if(count==6){
r1.setText("SuperMan");
r2.setText("Batman");
r3.setText("Shaktiman");
r4.setText("IronMan");
r1.setVisible(true);
r2.setVisible(true);
r3.setVisible(true);
r4.setVisible(true);
bb1.clearSelection();

q7validation();
}
else if(count==7){
r1.setText("White");
r2.setText("Black");

r1.setVisible(true);
r2.setVisible(true);
r3.setVisible(false);
r4.setVisible(false);
bb1.clearSelection();

q8validation();
}
if(count>7){
r1.setVisible(false);
r2.setVisible(false);
r3.setVisible(false);
r4.setVisible(false);
if(age>10&&age<40){
JOptionPane.showMessageDialog(rootPane,"Thanks for your valuable time, Play the game if you want ");
b100.setEnabled(true);
}
else
    JOptionPane.showMessageDialog(rootPane,"Thanks for your valuable time, Play the game if you want");

b10.setEnabled(true);
}
count++;

// TODO add your handling code here:
    }//GEN-LAST:event_l1MouseClicked

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        String x[]=new String[ind];
        Random r = new Random();
		int z=r.nextInt(7);
     
        String arr[]={" Teach your kids the “language of feelings”.\n" +
"\n" +
"One of the most important things you can teach your children is to recognize what they are feeling and to express their feelings in words. Help your children grow by teaching the many words for different emotions, and using examples when those feelings arise in themselves and others.\n" +
"\n" +
"People’s actions can be “bad” but the feelings themselves are never “bad”. One reason children get stuck and don’t want to talk about feelings, even if you ask them to, is because they can confuse how they feel as being “bad” or “a problem” when it is actually the tough thing that happened that is the problem. Feelings are like important road signs, if we understand them and listen to them. They can teach us where to go next and what to look for.\n" +
"\n" +
"Many children shut down when they are upset because they think all feelings except for happy ones are negative and shameful. When you teach your kids the language for many different feelings and invite them to explore and share them, it makes difficult feelings normal and healthy. The result is the development of emotional smarts and social skills. They can deal with what they are feeling, and have stronger friendships too. This also helps them have better self-esteem.\n" +
"Even anger can be helpful when kids learn how to cope with it. The emotion of anger brings awareness that something is hurtful. When we recognize that we are hurt, our problem-solving skills can improve.","2.  Learn to put yourself in your child’s shoes.\n" +
"\n" +
"Pause and really listen to your child before offering advice or getting angry. This helps your child trust you and listen more openly to the advice you decide to give. When children are upset, be careful to understand their point of view and validate that they feel that way whether or not you agree. Children, along with adults, can better accept a different view of a situation once their emotions have been accepted and understood. Hearing the child’s viewpoint can reduce their defensive reaction. This doesn’t mean there is no consequence for breaking rules, but it means they can express what happened, "
                + "or what their thought process was, so they can grow. Children who grow up with their feelings not accepted will struggle in the future."
 ," Be aware of your child’s overall actions and behaviour.\n" +
"\n" +
"Children often show us they are having a problem through their behaviour rather than words. If your child is acting out and getting into trouble often, it is a clue that something needs to be problem-solved or that they need emotional support to cope and move forward. This is a reason why the language of feelings is so important. It isn’t healthy if your child can’t tell you what is going on. When kids are acting out, there are reasons and many things can be done to help. Don’t be afraid to ask for help even if the difficulty doesn’t seem extremely serious. All children need guidance about emotions"
                + " and relationships. If you ask for help or learn more about emotions and relationships yourself, you and your children will benefit."
        ,"Encourage creativity.\n" +
"\n" +
"All children need help to learn about their emotions and relationships. It is our job as adults to teach them these skills. Every child is different so we need to figure out what reaches each child individually. Look to what they truly enjoy to help them express themselves. Play, games, sports, art, writing, dance, horticulture, photography, music, and acting or role playing situations are great ways of helping kids learn to cope with difficult feelings and relationships. Creativity is a natural"
                + " human way to learn and express ourselves. If your child has learned that feelings should be avoided, creativity can open them to emotions."
        ," Show kids that having a mix of struggle and strength is normal for everyone.\n" +
"\n" +
"Teach your child that every person will experience times of strength and times of struggle. There is no shame in struggling. Often children are taught to focus way too much on the struggles they are having and get “stuck”, thinking they aren’t good enough. We need to help children balance the amount of time they focus on what is hard for them to learn and what their natural skills and passions are. Helping them build on what they naturally love is the secret to helping them grow self-esteem.\n" +
"\n" +
"Counselling, social skill groups, life coaching and leisure activities are great ways of helping kids build skills they will need to be the best they can be. Taking your children to counselling, for example, to learn new coping skills in an area difficult for them, can be a big help to their growth and development. It does not mean that something is wrong with them. In fact, it makes them healthier, stronger and more confident people.",
 "Break the cycle.\n" +
"\n" +
"Many adults grew up being shut down and ashamed of their feelings. They tried to ignore them in order to get through tough times. We pass this on to kids unintentionally. Children are like mirrors that reflect back what they see in their environments. Teach your kids to grow emotionally by showing them you aren’t afraid to express feelings and to cope in a positive way. Don’t shame your children for having tough feelings or being upset. If you don’t know how, ask for help. There is nothing wrong with needing help. If your children need help, you want them to be able to ask for it, so it is important that you show them you are able to ask for help as well.\n" +
"\n" +
"If you lose your temper, first apologize; next, show your kids how to grow by making emotionally healthy choices yourself. Teach them by example to take responsibility for their actions. Show them it is normal to make a mistake. It isn’t your fault if you didn’t learn these skills in your childhood. It is likely that your parents weren’t aware of how to cope with their difficult emotions in a healthy way either. Fear of feeling gets passed through generations. You can make a change for the better if you aren’t afraid to challenge yourself and learn new ways to connect with your child."
        ,"The way kids think is very important.\n" +
"\n" +
"Negative thinking about the self is a huge problem for many North American people of all ages. This thinking often starts in childhood. Children are getting constant messages that they may not be good enough. Many children get “stuck” in thinking this way from hearing negative messages about themselves and then repeating them over and over in their thoughts. Repetitive negative thinking about the self, others and the world can lead to future mental health struggles.\n" +
"\n" +
"Notice your child’s language and comments about him or herself and others. If your child says negative things repeatedly, it is a problem. It usually means they aren’t feeling good about themselves and need support to problem-solve and change that type of thinking. When kids practice negative self-talk, it leads to lower self esteem and can contribute to low mood and worry. It can leave them more vulnerable to being bullied as well. Bullying is dangerous to self esteem especially if children already believe they are not good enough. Look out for your child’s inner bully. Negative thinking is dangerous to mental health because it builds on itself. It becomes automatic to think painful and self damaging thoughts, much like learning an instrument or a sport, but with a negative result rather than a positive one.\n" +
"\n" +
"Our brains are designed to change when we repeat thoughts and actions over and over. For example, picture yourself and your child skiing or tobogganing. If you go over the same path again and again it will soon get very slippery and grooved in. It becomes faster and faster for the two of you to slide down that path. Our brains work in a similar way. If you and your child are rehearsing painful or mean thoughts, you may have become very good at something that hurts you. To change negative thinking patterns, the person must start a different and positive path and practice that instead. Once people get used to a new positive path, they follow it automatically and they start to feel happier."};
int danger=0;
        
    if(ans[0]=="no"){
        x[0]=name +" does not love chocolates but "+name+" it is okay to have some chocolates";
    danger++;
    }else
        x[0]="* Chocolates are good but excess can lead to problem";
if(ans[2]=="No"){
          x[1]="* Cartoons is a must part for a child of age" + age+" .I would recommend the parents to"
                  + " make sure that the child watches any type of cartoon";
danger++;
}else           
          x[1]="* "+name+" loves watching cartoons which is a good thing";
        if(ans[4]=="No"){
x[2]="*  Parents are requested to give proper time to "+name+ " and on certain days take the child for an outing";
        danger++;
        }else
            x[2]="*  Parents are the most loyal and most caring ";
        if(ans[5]=="Indoor"){
            x[3]="* Parents are requested that the child be taken out for outdoor games as this causes mental "
                    + "anxiety to a child";
            danger++;
        }
        else    
        x[3]="* OutDoor Games is always a Joy ";
                    
         
               ta.setText("\t    Well Done "+ name+"\n"
        + x[0]+"\n"+x[1]+"\n"+x[2]+"\n"+x[3]+"\n"+arr[z]);
           
           
         
           b10.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
feedback f = new feedback();
f.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void b100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b100ActionPerformed
String url="www.uk3.herokuapp.com";
    try {
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(working.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_b100ActionPerformed

    /**
     *      * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new working().setVisible(true);
            }
        });
    }
    public void q1validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else 
            ans[ind++]=r2.getText();
        }
    
    
    
     public void q2validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();

    } public void q3validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
         
    } public void q4validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
         
    } public void q5validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
         
    } public void q6validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
         
    } 
    public void q8validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
        for(int i=0;i<=ind;i++)
            System.out.println(ans[i]);
         
    } 
    public void q7validation(){
        if(r1.isSelected())
            ans[ind++]=r1.getText();
        else
            ans[ind++]=r2.getText();
         
        
    } 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public void connect(int i){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/myproject","root","uditkhanna112");
           String str= "select questions from child";
           
           st=con.createStatement();
           rs=st.executeQuery(str);
         int j=0;
           while(rs.next()){
               quesc[j]=rs.getString(i);
               j++;
           }
           num.setText("Hello and welcome "+name);
           
           
            con.close();
        }
        catch(ClassNotFoundException | SQLException e1){ System.out.println(e1);}
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b10;
    private javax.swing.JButton b100;
    private javax.swing.ButtonGroup bb1;
    private javax.swing.JDialog j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel ll1;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel num;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
